### ISSUE TITLE
Anki Deck not working

### ISSUE THREAD

**Issue by openmedi** [twhite96/front_end_interview_questions_flashcards#1]
Hey I tried to import the anki file into anki desktop (v. 2.0.52) and it gives me the following error:

>This file does not appear to be a valid .apkg file. If you're getting this error from a file downloaded from AnkiWeb, chances are that your download failed. Please try again, and if the problem persists, please try again with a different browser.

Any help is appreciated. And thanks for all the work!

**Comment by openmedi** [comment]
Nevermind. Downloading again (a second time) did the trick.

**Comment by twhite96** [comment]
Thanks for raising this issue. I'm glad you got it to work. Will check this out to see if I can't prevent the initial download from failing again.
